name: Cypress CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout testes Cypress
        uses: actions/checkout@v4

      - name: Checkout aplicação Hub de Leitura
        uses: actions/checkout@v4
        with:
          repository: EBAC-QE/hub-de-leitura-integrado
          path: app

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências da aplicação
        working-directory: ./app
        run: npm install

      - name: Inicializar banco de dados
        working-directory: ./app
        run: npm run db

      - name: Iniciar aplicação
        working-directory: ./app
        run: npm start &

      - name: Instalar dependências dos testes
        run: npm install

      - name: Aguardar aplicação
        run: npm run wait
        
      - name: Executar testes Cypress
        run: npm test